var first_name = "Ranbir";
console.log(first_name);
var last_name = "Kapoor";
console.log(last_name);
var A = 10;
var B = 5;
var add = a + b;
console.log(add); 
var full_name = first_name.concat(last_name);
console.log(full_name);
